<pre>Co-variance of a Data Matrix
It is a dxd matrix.
if X is a nxd matrix.
n = number of rows
d = number of columns/features.

         f1 f2 f3 ..... fi.... fd
      x1[                       ]
      x2[                       ]
X =   x3[                       ]
      x4[                       ]
       .
       .
       .
      xn[                       ](nxd)
      
If X is column stantardised. Means for every column in X, mean(column) = 0, std(column) = 1

Then Co - variance matrix of X will be

S = (X.Transpose . X) / n     dot prod of X trancpose and X, divided by n
</pre>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel('sample_matrix.xlsx')
data

sl   sw   pl   pw species
0   5.1  3.5  1.4  0.2  setosa
1   4.9  3.0  1.4  0.2  setosa
2   4.7  3.2  1.3  0.2  setosa
3   4.6  3.1  1.5  0.2  setosa
4   5.0  3.6  1.4  0.2  setosa
5   5.4  3.9  1.7  0.4  setosa
6   4.6  3.4  1.4  0.3  setosa
7   5.0  3.4  1.5  0.2  setosa
8   4.4  2.9  1.4  0.2  setosa
9   4.9  3.1  1.5  0.1  setosa
10  5.4  3.7  1.5  0.2  setosa
11  4.8  3.4  1.6  0.2  setosa
12  4.8  3.0  1.4  0.1  setosa
13  4.3  3.0  1.1  0.1  setosa
14  5.8  4.0  1.2  0.2  setosa
15  5.7  4.4  1.5  0.4  setosa
16  5.4  3.9  1.3  0.4  setosa
17  5.1  3.5  1.4  0.3  setosa
18  5.7  3.8  1.7  0.3  setosa

<pre>OK so following the notation. We have a dataset with 5 features. We have total 19 datapoints.
d = 5
n = 19
f1  = sl
f2 = sw
f3 = pl
f4 = pw
f5 = species

we have 19 x 5 matrix.
</pre>

In [4]:
# Function to perform column standardization
# For column standardization we need mean() and std() of each column.

def col_standard(column):
    c_mean = column.mean()
    c_std = column.std()
    col_s = []
    
    for value in column:
        col_s.append( ((value - c_mean) / c_std) )   # formula for column standardization
    
    return col_s

In [6]:
# Performing column standardization
standard_matrix = pd.DataFrame(list(zip( col_standard(data['sl']), 
                                         col_standard(data['sw']), 
                                         col_standard(data['pl']), 
                                         col_standard(data['pw'])
                                       )), 
                            columns =['sl_dash', "sw_dash", "pl_dash", "pw_dash"])
standard_matrix

sl_dash   sw_dash   pl_dash   pw_dash
0   0.156035  0.089587 -0.211560 -0.333849
1  -0.300067 -1.126232 -0.211560 -0.333849
2  -0.756169 -0.639905 -0.881499 -0.333849
3  -0.984220 -0.883069  0.458380 -0.333849
4  -0.072016  0.332750 -0.211560 -0.333849
5   0.840188  1.062242  1.798259  1.780528
6  -0.984220 -0.153577 -0.211560  0.723339
7  -0.072016 -0.153577  0.458380 -0.333849
8  -1.440323 -1.369396 -0.211560 -0.333849
9  -0.300067 -0.883069  0.458380 -1.391037
10  0.840188  0.575914  0.458380 -0.333849
11 -0.528118 -0.153577  1.128319 -0.333849
12 -0.528118 -1.126232 -0.211560 -1.391037
13 -1.668374 -1.126232 -2.221378 -1.391037
14  1.752393  1.305406 -1.551439 -0.333849
15  1.524341  2.278061  0.458380  1.780528
16  0.840188  1.062242 -0.881499  1.780528
17  0.156035  0.089587 -0.211560  0.723339
18  1.524341  0.819078  1.798259  0.723339

In [7]:
X = standard_matrix.to_numpy()

In [8]:
X

array([[ 0.15603496,  0.08958666, -0.21155983, -0.33384893],
       [-0.30006722, -1.12623231, -0.21155983, -0.33384893],
       [-0.7561694 , -0.63990472, -0.88149931, -0.33384893],
       [-0.98422049, -0.88306851,  0.45837964, -0.33384893],
       [-0.07201613,  0.33275045, -0.21155983, -0.33384893],
       [ 0.84018822,  1.06224184,  1.79825859,  1.78052763],
       [-0.98422049, -0.15357713, -0.21155983,  0.72333935],
       [-0.07201613, -0.15357713,  0.45837964, -0.33384893],
       [-1.44032267, -1.3693961 , -0.21155983, -0.33384893],
       [-0.30006722, -0.88306851,  0.45837964, -1.39103721],
       [ 0.84018822,  0.57591425,  0.45837964, -0.33384893],
       [-0.52811831, -0.15357713,  1.12831911, -0.33384893],
       [-0.52811831, -1.12623231, -0.21155983, -1.39103721],
       [-1.66837376, -1.12623231, -2.22137825, -1.39103721],
       [ 1.75239258,  1.30540563, -1.55143878, -0.33384893],
       [ 1.52434149,  2.27806081,  0.45837964,  1.78052763],
       [ 0.84018822,  1.

In [14]:
X.shape

# n = 19
# d = 4

(19, 4)

In [15]:
n = 19
S = (np.dot(X.transpose(), X)) / n    # calculating Co-variance Matrix S

In [16]:
S

array([[0.94736842, 0.83825821, 0.29836621, 0.53427798],
       [0.83825821, 0.94736842, 0.23330165, 0.70640818],
       [0.29836621, 0.23330165, 0.94736842, 0.3394117 ],
       [0.53427798, 0.70640818, 0.3394117 , 0.94736842]])

In [28]:
print(X.transpose()) 

# 19 columns: x0,x1,x2......x18
# 4 rows: f1, f2, f3, f4

[[ 0.15603496 -0.30006722 -0.7561694  -0.98422049 -0.07201613  0.84018822
  -0.98422049 -0.07201613 -1.44032267 -0.30006722  0.84018822 -0.52811831
  -0.52811831 -1.66837376  1.75239258  1.52434149  0.84018822  0.15603496
   1.52434149]
 [ 0.08958666 -1.12623231 -0.63990472 -0.88306851  0.33275045  1.06224184
  -0.15357713 -0.15357713 -1.3693961  -0.88306851  0.57591425 -0.15357713
  -1.12623231 -1.12623231  1.30540563  2.27806081  1.06224184  0.08958666
   0.81907804]
 [-0.21155983 -0.21155983 -0.88149931  0.45837964 -0.21155983  1.79825859
  -0.21155983  0.45837964 -0.21155983  0.45837964  0.45837964  1.12831911
  -0.21155983 -2.22137825 -1.55143878  0.45837964 -0.88149931 -0.21155983
   1.79825859]
 [-0.33384893 -0.33384893 -0.33384893 -0.33384893 -0.33384893  1.78052763
   0.72333935 -0.33384893 -0.33384893 -1.39103721 -0.33384893 -0.33384893
  -1.39103721 -1.39103721 -0.33384893  1.78052763  1.78052763  0.72333935
   0.72333935]]


In [31]:
np.dot(X.transpose(), X)

array([[18.        , 15.92690591,  5.66895793, 10.15128163],
       [15.92690591, 18.        ,  4.43273144, 13.42175546],
       [ 5.66895793,  4.43273144, 18.        ,  6.44882229],
       [10.15128163, 13.42175546,  6.44882229, 18.        ]])

In [27]:
np.dot(X.transpose(), X) / n

array([[0.94736842, 0.83825821, 0.29836621, 0.53427798],
       [0.83825821, 0.94736842, 0.23330165, 0.70640818],
       [0.29836621, 0.23330165, 0.94736842, 0.3394117 ],
       [0.53427798, 0.70640818, 0.3394117 , 0.94736842]])

In [29]:
np.dot(X.transpose()/n, X/n)

array([[0.0498615 , 0.04411885, 0.01570348, 0.02811989],
       [0.04411885, 0.0498615 , 0.01227903, 0.03717938],
       [0.01570348, 0.01227903, 0.0498615 , 0.01786377],
       [0.02811989, 0.03717938, 0.01786377, 0.0498615 ]])