# Numpy Arrays

## python objects

1. High level number objects: Int and float
2. containers: Lists(costless insertion and append), dictionary(fast lookup)

## Numpy Provides

1. extension package to Python for multi dimensional arrays.
2. cloaser to hardware (efficiency)
3. design for scientific computation (convenience)
4. Also known as array oriented computing

In [1]:
# Basic exapmle of numpy array

In [2]:
import numpy as np

In [3]:
a = np.array([1,66,7,33,7])  # by passing a list
print(a)
type(a)

[ 1 66  7 33  7]


numpy.ndarray

In [4]:
arr = np.arange(10)   # using arange() function
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


# Why we shoud use numpy arrays.

In [5]:
# OK so here we will analyse how fast numpy arrays are.
# We will perform same operation using a list and a numpy array. Then we will see how much time that operation has taken.
# We will use %timeit to calculate the mean time per execution. This function will run the operation/expression again and
# again to calculate the mean operation time.
# for now we will apply %timeit to only single line statement.

In [20]:
lst = range(1000)
%timeit [ x**2 for x in lst ]

1.5 ms ± 202 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
arr = np.arange(1000)
%timeit arr ** 2

4.99 µs ± 663 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### We can clearly see the difference in the performance of both list and np array.
### np.array <<< list
Which makes np.array super efficent for numerical operations.

# 1. Creating Arrays

### 1-D array

In [22]:
# 1-D arrays

a = np.array([1,5,7,3])

a

array([1, 5, 7, 3])

In [23]:
# check dimensions

a.ndim

1

In [24]:
# Check shape

a.shape

(4,)

In [25]:
# length of array, also means total number of elements in the array

len(a)

4

### 2-D array

In [35]:
# Creating 2d array

b = np.array([ [1,2,3], [8,9,7], [5,9,3], [4,8,3] ])

b

array([[1, 2, 3],
       [8, 9, 7],
       [5, 9, 3],
       [4, 8, 3]])

In [54]:
type(b)

numpy.ndarray

In [36]:
# Dimension
b.ndim

2

In [37]:
# shape
b.shape   # 2 rows and 3 columns

(4, 3)

In [38]:
len(b) # Here length will return number of rows

4

### 3-D array

In [55]:
c = np.array([ [[10,20,30,40],[50,60,70,80],[1,2,3,4]] , [[11,22,33,44],[55,66,77,88],[1,2,3,4]] ])

In [58]:
c

array([[[10, 20, 30, 40],
        [50, 60, 70, 80],
        [ 1,  2,  3,  4]],

       [[11, 22, 33, 44],
        [55, 66, 77, 88],
        [ 1,  2,  3,  4]]])

In [57]:
print(type(c))

<class 'numpy.ndarray'>


In [48]:
c.ndim

3

In [49]:
c.shape  # 2 planes 3 rows and 4 columns

(2, 3, 4)

In [50]:
len(c)

2

### Functions for creating arrays.

### arange()

In [59]:
# Using arange function

# it similarly works as range() funtion of python.

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
b = np.arange(1,10,2) # start, end(exclusive), step
b

array([1, 3, 5, 7, 9])

### linspace()

In [61]:
# Using linspace (linearly spaced numbers)

c = np.linspace(1,10,6)   # start, end(inclusive), number of points.
c

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [63]:
d = np.linspace(10,100,10)
d

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## common arrays

### np.ones()

In [64]:
a = np.ones((2,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
b = np.ones((5,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.zeros()

In [67]:
x = np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [68]:
y = np.zeros((1,1))
y

array([[0.]])

### Identity matrix

In [69]:
i = np.eye(3,2)
i

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [70]:
j = np.eye(5,5)
j

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diagonal matrix

In [77]:
# Given numbers at diagonals and remaining values are 0.

d = np.diag([1,88,3,66])
print(d)

[[ 1  0  0  0]
 [ 0 88  0  0]
 [ 0  0  3  0]
 [ 0  0  0 66]]


In [75]:
e = np.diag([1,1,1])
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [76]:
# How to extract diagonal values. Just passing the diagonal array in np.diag(arrayName) will return you diagonal elements

print(np.diag(d))
print(np.diag(e))

[ 1 88  3 66]
[1 1 1]


## Random Arrays

### np.random.rand()

In [2]:
# It will return array of uniformly distributed random numbers
u = np.random.rand(4)
print(u)

[0.14977515 0.94083923 0.28645067 0.59754572]


In [3]:
p = np.random.rand(4,3)
print(p)

[[0.12933096 0.53094464 0.56730052]
 [0.69193619 0.54730504 0.11704118]
 [0.18418674 0.59763398 0.29878584]
 [0.11548701 0.29497063 0.07184798]]


### np.random.randn()

In [82]:
# it will return array of Normaly distributed random numbers

n = np.random.randn(4)
n

array([-1.35095569, -0.4942767 ,  0.12669051,  0.34917224])

In [85]:
q = np.random.randn(4,6)
print(q)

[[-1.36961826 -0.2447183   2.02248542  0.1104481  -1.07531196 -0.5794767 ]
 [ 0.31336063  2.45242335  1.21875637 -0.65989619  0.15021938 -0.37005458]
 [ 0.36557966 -0.93161533 -0.2210681   0.90742507 -2.45141774  0.54956635]
 [-1.3271303   0.33782819  0.63699753  1.4175572  -0.4212082  -0.47738479]]


# 2. Basic Data Types

### Explicitly giving the datatype

In [90]:
a = np.arange(10)
print(a)
print(type(a))   # This will return type of object
print(a.dtype)   # This will return the datatype of elements of the array.

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


In [6]:
# We can explicitly change the type of array elements.

b = np.arange(10, dtype='float64')
b.dtype

# These . after number means they are float with 0 decimal values.

dtype('float64')

### dtype of ones and zeros

In [95]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [99]:
o2 = np.ones((3,3), dtype='int')
o2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [97]:
z = np.zeros((2,2), dtype='str')
z

array([['', ''],
       ['', '']], dtype='<U1')

## Array of Different DataTypes

### Complex Numbers

In [101]:
c = np.array([1+2j, 9+5j])
print(c)

print(c.dtype)

[1.+2.j 9.+5.j]
complex128


### bool

In [103]:
b = np.array([True, False, True, True])
print(b)
print('\n', b.dtype)

[ True False  True  True]

 bool


### str

In [106]:
s = np.array([['Dev', 'Kumar'],['Rahul', 'Singh']])
print(s)
s.dtype

[['Dev' 'Kumar']
 ['Rahul' 'Singh']]


dtype('<U5')

# 3. Indexing and Slicing

### Indexing

In [7]:
# Indexing in numpy arrays works same as in python sequenses like list and tuples.

In [11]:
a = np.arange(55,60)
print(a)

print(a[3])

[55 56 57 58 59]
58


In [14]:
a2 = np.diag([1,88,99])
print(a2)

print('\n', a2[1,1])

[[ 1  0  0]
 [ 0 88  0]
 [ 0  0 99]]

 88


In [16]:
a2[2,1] = 559  # assgning value
print(a2)

[[  1   0   0]
 [  0  88   0]
 [  0 559  99]]


### Slicing

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[1:8:2]

array([1, 3, 5, 7])

In [19]:
a[5:]

array([5, 6, 7, 8, 9])

In [22]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [20]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [21]:
a[5:] = b[::-1]   # Notice: this work requires loop. but slicing and assigning has done all the work.
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [23]:
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. We can use np.shares_memory() to check if two arrays share the same memory block.

#### When  modifying the subarray/sliced array/view, the original array is modified as well:

In [24]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [27]:
# Now numpy hasn't created a copy of array a, it is just showing
# the sliced view of a in b.
# To confirm that b is not a saparate copy. We will use 
# np.shares_memory() method.

np.shares_memory(a,b)

True

In [28]:
# It means a and b are pointing to same values in memory.
# Where b is pointing to only the values specified in slice operation.

In [29]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [30]:
# Now see this change is also occured in a or not.
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [32]:
# Yes chages are also happening in a as well as b. Because they are sharing the same memory.
# Python do that to use less memory.
# So we should use slice operation carefully

### force a copy

In [33]:
# We can create a saparate copy so our original array will reamin unchanged.

k = np.arange(8)
k

array([0, 1, 2, 3, 4, 5, 6, 7])

In [35]:
c = k[::2].copy()             # create saparate copy while slicing
c

array([0, 2, 4, 6])

In [36]:
np.shares_memory(k,c)         # checking memory sharing

False

In [37]:
c[2] = 999                    # change in sub array/view
c

array([  0,   2, 999,   6])

In [38]:
k                             # see original is changed or not.

array([0, 1, 2, 3, 4, 5, 6, 7])

# Fancy Indexing

Numpy arrays can be indexed with slice, but also with boolean or integer arrays(masks). This method is called fancy indexing.
<b>It creates copies not views.</b>

In [7]:
arr = np.random.randint(0, 10, 10)
# generate 15 random int values between 0 to 20
print(arr)

[1 1 8 7 8 0 7 2 6 5]


In [8]:
mask = (arr % 2 == 0)

In [9]:
extract_from_arr = arr[mask]

extract_from_arr

array([8, 8, 0, 2, 6])

In [10]:
arr

array([1, 1, 8, 7, 8, 0, 7, 2, 6, 5])

In [45]:
# So here we have masked values from arr.

### Assign a new value Using Mask

In [12]:
arr[mask] = 222
arr

# This code will assign value -1 where mask is True.
# Means where value is even.

array([  1,   1, 222,   7, 222, 222,   7, 222, 222,   5])

In [69]:
mask2 = (arr == -1)
mask2

array([ True,  True, False, False,  True, False,  True, False,  True,
       False,  True, False, False, False, False])

In [70]:
arr

array([-1, -1,  5, 11, -1,  7, -1,  7, -1, 17, -1, 19,  9,  7, 17])

In [75]:
arr[mask2] = 0

In [76]:
arr

array([ 0,  0,  5, 11,  0,  7,  0,  7,  0, 17,  0, 19,  9,  7, 17])

### Creating subarray using Index.

In [77]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
# Create a subarray using index.

b = a[[2,3,2,8,2]]
b

# Here we have performed slicing by giving exact index rather than some range

array([20, 30, 20, 80, 20])

In [84]:
b[1] = 555         # assigning a value

In [85]:
b

array([ 20, 555,  20,  80,  20])

In [86]:
a                 # Check for some change

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### assigning value on multiple indexes.

In [88]:
a[[2,8,9]] = -200
a

array([   0,   10, -200,   30,   40,   50,   60,   70, -200, -200])

In [89]:
b[[0, -1]] = 0
b

array([  0, 555,  20,  80,   0])

#### changes are permanent.

In [90]:
a

array([   0,   10, -200,   30,   40,   50,   60,   70, -200, -200])

In [91]:
b

array([  0, 555,  20,  80,   0])