In [1]:
import numpy as np

# Elementwise Operations

### 1. Basic Operations

#### with scalers

In [3]:
a = np.array([1,2,3,4])   # numpy arrays are also treated as vectors.

a + 1      # So we can say we are adding a scaler 1 to vector a.

array([2, 3, 4, 5])

In [4]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

### All arithmetic operates elementwise

In [8]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [9]:
a - b

array([-1.,  0.,  1.,  2.])

In [10]:
a * b

array([2., 4., 6., 8.])

In [15]:
# Matrix Multiplication.

c = np.array([[1,2,3],[10,20,30],[0,0,0]])
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 0,  0,  0]])

In [16]:
c * c

array([[  1,   4,   9],
       [100, 400, 900],
       [  0,   0,   0]])

In [17]:
c.dot(c)

array([[ 21,  42,  63],
       [210, 420, 630],
       [  0,   0,   0]])

### Comparisions

In [18]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])

In [19]:
a == b     # This will perform element wise comparision

array([False,  True, False,  True])

In [20]:
a > b      # same for this operation

array([False, False,  True, False])

#### np.array_equal()

In [21]:
# We can use array_equal() to compair two arrays are same or not.

np.array_equal(a,b)

False

In [22]:
c = np.array([1,2,3,4])

np.array_equal(a,c)

True

## Logical Operations

In [23]:
# Here we will perform logical operations on two arrays. Not a complex concept.

In [25]:
a = np.array([1,1,0,0])   # we can set the dtype=bool
b = np.array([0,1,0,1])

np.logical_or(a,b)

array([ True,  True, False,  True])

In [26]:
np.logical_and(a,b)

array([False,  True, False, False])

In [29]:
np.logical_not(a)

array([False, False,  True,  True])

### Transcedental functions:

In [30]:
a = np.arange(5)

In [31]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
np.log(a)

C:\Users\BabaJi\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [33]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape Mismatch

In [34]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [35]:
b = np.array([5,9])
b

array([5, 9])

In [38]:
# a + b

# Here we will get an error because shapes of both arrays are not same.

<code>ValueError: operands could not be broadcast together with shapes (4,) (2,)</code>

### computing sums

In [39]:
x = np.array([1,2,3,4])

np.sum(x)

10

In [40]:
# Sum by rows and columns

x = np.array([ [1,5],[4,6] ])
x

array([[1, 5],
       [4, 6]])

In [42]:
x.sum(axis=0)   # Column wise sum (1+4), (5+6)

array([ 5, 11])

In [45]:
x.sum(axis=1)   # Row wise sum (1+5), (4+6)

array([ 6, 10])

## simple reductions

In [46]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [47]:
x.min()

1

In [48]:
x.max()

3

In [49]:
x.argmin()   # Index of minimum value

0

In [50]:
x.argmax()   # index of max value

2

### Other logical Operations

In [3]:
p = np.array([True, True, False])
print(p)

q = np.array([1, 0, 0])
print(q)

[ True  True False]
[1 0 0]


In [6]:
# any() if any one element is True returns True.   Same ar OR
 
print('p', np.any(p))
print('q', np.any(q))

p True
q True


In [7]:
# all() iff all elements are True only then True, otherwise returns False.

print('p', np.all(p))
print('q', np.all(q))

p False
q False


In [8]:
np.all([1,1,1,1])

True

In [9]:
np.all([True, True])

True

#### use of any or all in more meaningfull way.

In [13]:
a = np.array([50, 50, 50, 50])

np.any(a == 0)   # See if ANY value in a is equal to 0

False

In [14]:
np.all(a > 0)  #  see if ALL values are positive

True

In [16]:
np.all(a == a)  # See if ALL values are equal to each other.

True

#### comparing array values without any loop

In [24]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).all()

# It this code block, we are comparing element wise.
# 0th ele of a is compared with 0th ele of b.
# 1st ele of a is compared with 1st ele of b.

# a <= b will return this array [T, T, T, T]
# b <= c will return this array [T, T, T, T]

# Then their & opertion [T, T, T, T] & [T, T, T, T] ==>  [T, T, T, T]
# Now its all()
# [T, T, T, T].all()  ==> True

True

In [22]:
a = np.array([9,9,9,9])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])

((a <= b) & (b <= c)).any()    # all values of a shoud be greator than b to make this any() false. Their are other cases also.

False

### Statistics 

In [26]:
x = np.array([1,2,3,1])
print(x.mean())           # Mean,  it's a function of array itself
print(np.median(x))       # Median,  it's a function of Numpy.

1.75
1.5


<b>For 2d Array<b/>

In [27]:
y = np.array([[1,2,3], [4,8,9]])

In [28]:
y.mean()   # Mean of all values

4.5

In [32]:
y.mean(axis=0)  # Column wise mean()

array([2.5, 5. , 6. ])

In [33]:
y.mean(axis=1)  # row wise mean()

array([2., 7.])

In [34]:
np.median(y)  # Median of all values

3.5

In [35]:
np.median(y, axis=0)  # colunm wise

array([2.5, 5. , 6. ])

In [36]:
np.median(y, axis=1) # row wise

array([2., 8.])