In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([8,9,10])

In [21]:
b

array([ 8,  9, 10])

In [22]:
bt = b.transpose()

In [17]:
a*b

array([ 8, 18, 30])

In [23]:
bt

array([ 8,  9, 10])

In [19]:
a*bt

array([ 8, 18, 30])

In [20]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Original Array:\n{arr1}')

arr1_transpose = arr1.transpose()

print(f'Transposed Array:\n{arr1_transpose}')

Original Array:
[[1 2 3]
 [4 5 6]]
Transposed Array:
[[1 4]
 [2 5]
 [3 6]]


In [29]:
at = np.array([a]).transpose()

In [30]:
at

array([[1],
       [2],
       [3]])

In [31]:
at*b

array([[ 8,  9, 10],
       [16, 18, 20],
       [24, 27, 30]])

In [32]:
b

array([ 8,  9, 10])